alias rcreds='rails credentials:edit'
alias rdev='bin/dev'
alias rc='rails console'
alias rseed='rails db:seed'
alias rubo='rubocop -A'
alias rtest='rails test'
alias rubotest='rubocop -A && rails test'
alias b='bundle'
alias ba='bundle add'

alias dc='docker-compose'
alias dcup='docker-compose up'
alias dcdown='docker-compose down'
